pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/devika089999/aws-s3-etl-demo', branch: 'main'
            }
        }

        stage('Archive Files') {
            steps {
                // Archive all files into a single zip
                sh 'zip -r artifact.zip *'
            }
        }

        stage('Upload to S3') {
            steps {
                step([
                    $class: 'S3UploadPublisher',
                    profileName: 'aws-s3-creds', // this should match the AWS credentials ID
                    entries: [[
                        bucket: 'jenki123',
                        sourceFile: 'artifact.zip',
                        selectedRegion: 'us-east-2', // change region if needed
                        noUploadOnFailure: true,
                        flatten: true
                    ]]
                ])
            }
        }
    }

    post {
        success {
            echo "✅ Files uploaded to S3 successfully."
        }
        failure {
            echo "❌ Upload failed."
        }
    }
}